INSERT INTO tb_role (authority) VALUES ('VISITOR');
INSERT INTO tb_role (authority) VALUES ('MEMBER');

INSERT INTO tb_user ( name, email, password) VALUES ( 'Bob', 'bob@gmail.com', '123456');
INSERT INTO tb_user ( name, email, password) VALUES ( 'ana', 'ana@gmail.com', '123456');
INSERT INTO tb_user ( name, email, password) VALUES ( 'maria', 'maria@gmail.com', '123456');
INSERT INTO tb_user ( name, email, password) VALUES ( 'lucas', 'lucas@gmail.com', '123456');

INSERT INTO tb_user_role ( user_id, role_id) VALUES ( 1, 1);
INSERT INTO tb_user_role ( user_id, role_id) VALUES ( 2, 2);
INSERT INTO tb_user_role ( user_id, role_id) VALUES ( 3, 1);
INSERT INTO tb_user_role ( user_id, role_id) VALUES ( 3, 2);
INSERT INTO tb_user_role ( user_id, role_id) VALUES ( 4, 2);

INSERT INTO tb_genre ( name) VALUES ( 'Ação');
INSERT INTO tb_genre ( name) VALUES ( 'Animação');
INSERT INTO tb_genre ( name) VALUES ( 'Ficção científica');
INSERT INTO tb_genre ( name) VALUES ( 'Fantasia');
INSERT INTO tb_genre ( name) VALUES ( 'Terror');
INSERT INTO tb_genre ( name) VALUES ( 'Romance');
INSERT INTO tb_genre ( name) VALUES ( 'Guerra');

INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Mad Max', 'Estrada da fúria', 2015, 'https://www.themoviedb.org/t/p/w220_and_h330_face/mE9ShTg5UoOIgo1LTkC1iZGMN1o.jpg', 'Em um mundo apocalíptico, Max Rockatansky acredita que a melhor forma de sobreviver é não depender de ninguém. Porém, após ser capturado pelo tirano Immortan Joe e seus rebeldes, Max se vê no meio de uma guerra mortal, iniciada pela imperatriz Furiosa que tenta salvar um grupo de garotas. Também tentando fugir, Max aceita ajudar Furiosa. Dessa vez, o tirano Joe está ainda mais implacável pois teve algo insubstituível roubado.', 1);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Os Vingadores', 'The Avengers', 2012, 'https://www.themoviedb.org/t/p/w220_and_h330_face/u49fzmIJHkb1H4oGFTXtBGgaUS1.jpg', 'Loki, o irmão de Thor, ganha acesso ao poder ilimitado do cubo cósmico ao roubá-lo de dentro das instalações da S.H.I.E.L.D. Nick Fury, o diretor desta agência internacional que mantém a paz, logo reúne os únicos super-heróis que serão capazes de defender a Terra de ameaças sem precedentes. Homem de Ferro, Capitão América, Hulk, Thor, Viúva Negra e Gavião Arqueiro formam o time dos sonhos de Fury, mas eles precisam aprender a colocar os egos de lado e agir como um grupo em prol da humanidade.', 1);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Missão: Impossível', 'Efeito Fallout', 2018, 'https://www.themoviedb.org/t/p/w220_and_h330_face/kVv60GGRuh3kF6KI5Hn2T7QWWx0.jpg', 'Em uma perigosa tarefa para recuperar plutônio roubado, Ethan Hunt opta por salvar sua equipe em vez de completar a missão. Com isso, armas nucleares caem nas mãos de agentes altamente qualificados e que pertencem a uma rede mortal que deseja destruir a civilização. Agora, com o mundo em risco, Ethan e sua equipe da IMF são forçados a aliar-se a um obstinado agente da CIA.', 1);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Toy Story', 'Um Mundo de Aventuras', 1995, 'https://www.themoviedb.org/t/p/w220_and_h330_face/6AafgfifXkFS4g2xGJZIwsPQK6P.jpg', 'Quando um reluzente ranger do espaço chamado Buzz Lightyear invade o mundo de um cowboy de corda chamado Woody, desencadeia uma hilariante briga entre brinquedos. Agora o favoritismo de Woody no coração do seu jovem dono está em perigo... assim como as vidas de Buzz e Woody.', 2);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Zootopia', 'Essa cidade é um bicho', 2016, 'https://www.themoviedb.org/t/p/w220_and_h330_face/kyiEmCk6mOenJiL7s3LspVKkoZM.jpg', 'Judy Hopps é a pequena coelha de uma fazenda isolada, filha de agricultores que plantam cenouras há décadas. Mas ela tem sonhos maiores: pretende se mudar para a cidade grande, Zootopia, onde todas as espécies de animais convivem em harmonia, na intenção de se tornar a primeira coelha policial. Judy enfrenta o preconceito e as manipulações dos outros animais, mas conta com a ajuda inesperada da raposa Nick Wilde, conhecida por sua malícia e suas infrações. A inesperada dupla se dedica à busca de um animal desaparecido, descobrindo uma conspiração que afeta toda a cidade.', 2);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Star Wars', 'O Despertar da Força', 2015, 'https://www.themoviedb.org/t/p/w220_and_h330_face/mc9hsb5BTTFGmPhHkXxonKP5rFN.jpg', 'A queda de Darth Vader e do Império levou ao surgimento de uma nova força sombria: a Primeira Ordem. Eles procuram o jedi Luke Skywalker, desaparecido. A resistência tenta desesperadamente encontrá-lo antes para salvar a galáxia.', 3);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Elysium', NULL, 2013, 'https://www.themoviedb.org/t/p/w220_and_h330_face/2QxAzqKf56IMHMMbPkaIkb3Ul6S.jpg', 'Em 2159, o mundo é dividido entre dois grupos: o primeiro, riquíssimo, mora na estação espacial Elysium, enquanto o segundo, pobre, vive na Terra, repleta de pessoas e em grande decadência. Por um lado, a secretária do governo Rhodes faz de tudo para preservar o estilo de vida luxuoso de Elysium, por outro, um pobre cidadão da Terra tenta um plano ousado para trazer de volta a igualdade entre as pessoas.', 3);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'O Senhor dos Anéis', 'A Sociedade do Anel', 2001, 'https://www.themoviedb.org/t/p/w220_and_h330_face/tlvsNCwWEIgwAM23aNzTmMIcPEZ.jpg', 'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove pessoas que formam a Sociedade do Anel.', 4);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Harry Potter', 'e a Pedra Filosofal', 2001, 'https://www.themoviedb.org/t/p/w220_and_h330_face/qnw9610ojLT0jU3lMSZOAFttt1e.jpg', 'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursleys. Ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente, Harry é impedido de ler a carta por seu tio, mas logo recebe a visita de Hagrid, o guarda-caça de Hogwarts, que chega para levá-lo até a escola. Harry adentra um mundo mágico que jamais imaginara, vivendo diversas aventuras com seus novos amigos, Rony Weasley e Hermione Granger.' , 4);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'O Chamado', NULL, 1998, 'https://www.themoviedb.org/t/p/w220_and_h330_face/6xed7epf3mfyb5RpqiRBEEm85rW.jpg', 'Após a morte de Tomoko Oishi, uma repórter, Reiko Asakawa, ouve histórias de um vídeo que mata quem o vê uma semana exatamente após assisti-lo. No início não dá importância aos rumores, mas ao descobrir que um amigo de Tomoko, que assistiu o vídeo, morreu exatamente uma semana depois ela começa a investigar. Após ver a fita estranhas coisas começam a acontecer.', 5);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'O Massacre da Serra Elétrica', NULL, 2003, 'https://www.themoviedb.org/t/p/w220_and_h330_face/peL5G7S7KER4y5fUAGgtGxRccbv.jpg', 'Um grupo de jovens está em meio a uma viagem do Texas para o México, até enfrentarem um problema: a gasolina do carro chega ao fim. Eles param bem em frente a um matadouro, onde começam a procurar desesperadamente por um telefone. Porém o que eles não sabem é que ali vive uma família de canibais, incluindo um homem que mata usando uma serra elétrica.', 5);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Titanic', NULL, 1997, 'https://www.themoviedb.org/t/p/w220_and_h330_face/cwRgiAjXREMbfr270MDZ73kQqIf.jpg', 'Um artista pobre e uma jovem rica se conhecem e se apaixonam na fatídica jornada do Titanic, em 1912. Embora esteja noiva do arrogante herdeiro de uma siderúrgica, a jovem desafia sua família e amigos em busca do verdadeiro amor.', 6);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Sniper Americano' , NULL, 2014, 'https://www.themoviedb.org/t/p/w220_and_h330_face/ha78BZ35Rh9VFt3fHnkwXcLAmPJ.jpg', 'História real de Chris Kyle, atirador de elite das forças especiais da marinha dos Estados Unidos. Durante a guerra do Iraque, sua missão era uma só- proteger seus companheiros. Seu dever fez dele um dos maiores atiradores da história americana. Sua precisão salva inúmeras vidas, mas também o torna um alvo preferencial. Quando Kyle finalmente volta para casa, ele descobre que não tem como deixar a guerra para trás.', 7);
INSERT INTO tb_movie ( title, sub_title, year, image_Url, synopsis, genre_id) VALUES ( 'Guerra ao Terror', NULL, 2008, 'https://www.themoviedb.org/t/p/w220_and_h330_face/lxayvkmq1Ka7aVUeujxLxwgcrD4.jpg', 'JT Sanborn, Owen Eldridge e Matt Thompson integram o esquadrão antibombas do exército americano em missão no Iraque. Eles trabalham na destruição de um explosivo, para que seja detonado sem atingir alguém. Entretanto, um erro faz com que o artefato exploda e mate Thompson. Em seu lugar é enviado o sargento William James, que possui muito sangue-frio, o que incomoda Sanborn. Apesar disto, o trio segue na ativa, tendo consciência de que cada dia concluído de trabalho é um dia a mais de vida.', 7);
